disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Simran Kriplani"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/cat.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Simran's Portfolio"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "Simran Kriplani"
   email = "paws.simran@gmail.com"
   image = "img/cat.jpg"
   imageQuality = 96
   headline = "Biology & Psychology at the University of Toronto"
   bio = ""
   links = [
     { email = "mailto:paws.simran@gmail.com" },
     { github = "https://github.com/simran-kriplani" },
     { instagram = "https://instagram.com/sim_ran_awayyy" },
     { linkedin = "https://linkedin.com/in/simran-kriplani" }
        ]
